In [2]:
import pandas as pd
import numpy as np
import random
import csv
from pdb import set_trace
#%pdb
mypath = '../pilot_6_data/'
#mypath = 'C:/Users/KeK/OneDrive - University College London/Random_probes_last/Luca/'
import pandas

In [8]:
D['observer_details']

{u'Participant no.': u'test',
 'date': 'test',
 'expName': 'test',
 u'session': u'-999'}

In [9]:
D['experiment_details'].keys()

[2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 1

In [41]:
f = '../output/participant_test.pik'
import pickle
with open(f,'r') as of:
    D = pickle.load(of)

In [42]:
DE = D['experiment_details']

In [43]:
DE[2].keys()

['cat_4',
 'cat_5',
 'tone_hz',
 'tone_onset',
 'cat_1',
 'cat_2',
 'cat_3',
 'keys',
 'space',
 'question',
 'image_name',
 'load',
 'present_absent',
 'block_number',
 'RT_VS',
 'exemplar',
 'trueskill',
 'RT_TO',
 'trial_type',
 'image_number',
 'useless']

In [18]:
df = pd.DataFrame(columns=('lib', 'qty1', 'qty2'))
for i in range(5):
    df.loc[i] = [random.randint(-1,1) for n in range(3)]

ValueError: cannot set a row with mismatched columns

In [12]:
df = pd.DataFrame(columns = ['Image_Name','Cat.1','Cat.2','Cat.3','Cat.4','Cat.5','TS','Load','exemplar','question','present_absent','trial_type','tone_Hz','tone_onset','space','RT_TO','keys','RT_VS','useless','Trial_N_Block','Block'])


In [15]:
df

0 Block Cat.1 Cat.2 Cat.3 Cat.4 Cat.5 Image_Name Load RT_TO   ...    \
0   0.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
1   1.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
2  -1.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
3   1.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
4   1.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
5   0.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
6  -1.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
7   1.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
8   1.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
9  -1.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
10  0.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
11 -1.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
12  0.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
13  0.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
14  0.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
15 -1.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
16 -1.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
17  1.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
18  1.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
19  0.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
20  0.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
0   0.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
1   0.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
2   0.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
3   1.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
4   0.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
5  -1.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
6   0.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
7   0.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
8   0.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
..  ...   ...   ...   ...   ...   ...   ...        ...  ...   ...   ...     
12  0.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
13 -1.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
14  0.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
15 -1.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
16 -1.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
17 -1.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
18  0.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
19 -1.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
20 -1.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
0  -1.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
1   0.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
2  -1.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
3   1.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
4   1.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
5  -1.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
6   0.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
7   1.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
8   0.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
9  -1.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
10  0.0   NaN   NaN   NaN   NaN   NaN   NaN        NaN  NaN   NaN   ...     
11

In [12]:
cols = ['Image_Name','Cat.1','Cat.2','Cat.3','Cat.4','Cat.5','TS','Load','exemplar','question','present_absent','trial_type','tone_Hz','tone_onset','space','RT_TO','keys','RT_VS','useless','Trial_N_Block','Block']

In [14]:
df.columns

Index([u'Image_Name', u'Cat.1', u'Cat.2', u'Cat.3', u'Cat.4', u'Cat.5', u'TS',
       u'Load', u'exemplar', u'question', u'present_absent', u'trial_type',
       u'tone_Hz', u'tone_onset', u'space', u'RT_TO', u'keys', u'RT_VS',
       u'useless', u'Trial_N_Block', u'Block'],
      dtype='object')

In [16]:
    new = pd.DataFrame([[random.randint(-1,1) for n in range(21)]], columns = cols)


In [40]:
DE[4].keys()

['cat_4',
 'cat_5',
 'tone_hz',
 'tone_onset',
 'cat_1',
 'cat_2',
 'cat_3',
 'block_number',
 'space',
 'question',
 'image_name',
 'load',
 'present_absent',
 'exemplar',
 'trueskill',
 'RT_TO',
 'trial_type',
 'image_number']

In [36]:
cols

['Image_Name',
 'Cat.1',
 'Cat.2',
 'Cat.3',
 'Cat.4',
 'Cat.5',
 'TS',
 'Load',
 'exemplar',
 'question',
 'present_absent',
 'trial_type',
 'tone_Hz',
 'tone_onset',
 'space',
 'RT_TO',
 'keys',
 'RT_VS',
 'useless',
 'Trial_N_Block',
 'Block']

In [45]:
def dataframe_from_dict(DE):
    df = pd.DataFrame(index=DE.keys(), columns = cols)

    for t in DE.keys():
        row = [DE[t]['image_name'], 
            DE[t]['cat_1'],
               DE[t]['cat_2'],
               DE[t]['cat_3'],
               DE[t]['cat_4'],
               DE[t]['cat_5'],
               DE[t]['trueskill'],
               DE[t]['load'],
               DE[t]['exemplar'],
               DE[t]['question'],
               DE[t]['present_absent'],
               DE[t]['trial_type'],
               DE[t]['tone_hz'],
               DE[t]['tone_onset'],
               DE[t]['space'],
               DE[t]['RT_TO'],
               DE[t]['keys'],
               DE[t]['RT_VS'],
               DE[t]['useless'],
               0,
               DE[t]['block_number'],

        ]
        df.loc[t] = row
    return df

In [31]:
DE.keys()

[2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 1

In [46]:
df

Image_Name    Cat.1    Cat.2 Cat.3 Cat.4 Cat.5       TS Load  \
1   2009_004225.jpg      cat      NaN   NaN   NaN   NaN   12.729  low   
2   2010_001829.jpg    horse      NaN   NaN   NaN   NaN  19.2344  low   
3   2008_004270.jpg   person     sofa   NaN   NaN   NaN   19.244  low   
4   2011_002303.jpg      car   person   NaN   NaN   NaN  20.6957  low   
5   2010_005885.jpg      dog      NaN   NaN   NaN   NaN  20.0747  low   
6   2008_001040.jpg     boat      NaN   NaN   NaN   NaN    20.21  low   
7   2010_004662.jpg     boat      NaN   NaN   NaN   NaN  21.1986  low   
8   2010_005780.jpg     boat      NaN   NaN   NaN   NaN  16.8463  low   
9   2009_002594.jpg   bottle      NaN   NaN   NaN   NaN  19.0962  low   
10  2009_001568.jpg      dog      NaN   NaN   NaN   NaN  17.1026  low   
11  2008_005046.jpg   person      dog   NaN   NaN   NaN  20.7129  low   
12  2008_001836.jpg      cat      NaN   NaN   NaN   NaN  20.4639  low   

   exemplar question  ...  trial_type  tone_Hz tone_onset  space  RT_TO  keys  \
1       cat      NaN  ...      Normal  No tone       -999  space  6.666  None   
2     horse      NaN  ...      Normal  No tone       -999  space  6.666  None   
3      sofa      NaN  ...      Normal  No tone       -999  space  6.666  None   
4       car      NaN  ...      Normal  No tone       -999  space  6.666  None   
5       dog      NaN  ...      Normal  No tone       -999  space  6.666  None   
6      boat      NaN  ...      Normal  No tone       -999  space  6.666  None   
7      boat      NaN  ...      Normal  No tone       -999  space  6.666  None   
8      boat      NaN  ...      Normal  No tone       -999  space  6.666  None   
9    bottle     bird  ...      Normal  No tone       -999  space  6.666     q   
10      dog      NaN  ...      Normal  No tone       -999  space  6.666  None   
11      dog      NaN  ...      Normal  No tone       -999  space  6.666  None   
12      cat      cat  ...      Normal  No tone       -999  space  6.666     q   

   RT_VS useless Trial_N_Block Block  
1   None    None             0     1  
2   None    None             0     1  
3   None    None             0     1  
4   None    None             0     1  
5   None    None             0     1  
6   None    None             0     1  
7   None    None             0     1  
8   None    None             0     1  
9   6.66    -999             0     1  
10  None    None             0     1  
11  None    None             0     1  
12  6.66    -999             0     1  

[12 rows x 21 columns]

In [4]:
df = pd.DataFrame.from_dict(D['experiment_details'],orient='index')


In [21]:
df = pd.DataFrame.from_dict(D['experiment_details'],orient='index')
df.columns = ['Image_Name','Cat.1','Cat.2','Cat.3','Cat.4','Cat.5','TS','Load','exemplar','question','present_absent','trial_type','tone_Hz','tone_onset','space','RT_TO','keys','RT_VS','useless','Trial_N_Block','Block']


In [6]:
df.columns

Index([u'cat_4', u'cat_5', u'tone_hz', u'tone_onset', u'cat_1', u'cat_2',
       u'cat_3', u'block_number', u'space', u'question', u'image_name',
       u'load', u'present_absent', u'exemplar', u'trueskill', u'RT_TO',
       u'trial_type', u'image_number', u'keys', u'RT_VS', u'useless'],
      dtype='object')

In [8]:
df.columns = [u'Cat.1', u'Cat.5', u'tone_hz', u'tone_onset', u'cat_1', u'cat_2',
       u'cat_3', u'block_number', u'space', u'question', u'image_name',
       u'load', u'present_absent', u'exemplar', u'trueskill', u'RT_TO',
       u'trial_type', u'image_number', u'keys', u'RT_VS', u'useless']

In [9]:
df

Cat.1   cat_5  tone_hz  tone_onset         cat_1         cat_2  \
2           NaN     NaN  No tone        -999           cat           NaN   
3           NaN     NaN  No tone        -999         horse           NaN   
4           NaN     NaN  No tone        -999        person          sofa   
5           NaN     NaN  No tone        -999           car        person   
6           NaN     NaN  No tone        -999           dog           NaN   
7           NaN     NaN  No tone        -999          boat           NaN   
8           NaN     NaN  No tone        -999          boat           NaN   
9           NaN     NaN  No tone        -999          boat           NaN   
10          NaN     NaN  No tone        -999        bottle           NaN   
11          NaN     NaN  No tone        -999           dog           NaN   
12          NaN     NaN  No tone        -999        person           dog   
13          NaN     NaN  No tone        -999           cat           NaN   
14          NaN     NaN  No tone        -999           car           NaN   
15          NaN     NaN  No tone        -999        person        bottle   
16          NaN     NaN  No tone        -999        person          boat   
17          NaN     NaN  No tone        -999        person           NaN   
18          NaN     NaN  No tone        -999        person           NaN   
19          NaN     NaN  No tone        -999        person           cat   
20          NaN     NaN  No tone        -999         horse           NaN   
21          NaN     NaN  No tone        -999           dog           NaN   
22          NaN     NaN  No tone        -999        person           NaN   
23          NaN     NaN  No tone        -999        bottle           NaN   
24          NaN     NaN  No tone        -999          boat           NaN   
25          NaN     NaN  No tone        -999           cat           NaN   
26          NaN     NaN  No tone        -999          sofa        person   
27          NaN     NaN  No tone        -999         chair   diningtable   
28          NaN     NaN  No tone        -999          bird           NaN   
29          NaN     NaN    tone1         765           dog        bottle   
30          NaN     NaN  No tone        -999     aeroplane           NaN   
31          NaN     NaN  No tone        -999          boat           NaN   
..          ...     ...      ...         ...           ...           ...   
932   tvmonitor   chair  No tone        -999        person        bottle   
933         NaN     NaN  No tone        -999        person         horse   
934         NaN     NaN  No tone        -999          sofa         chair   
935         NaN     NaN  No tone        -999        person          sofa   
936         NaN     NaN  No tone        -999        person          bird   
937         NaN     NaN  No tone        -999   pottedplant         chair   
938         NaN     NaN  No tone        -999          boat           cow   
939         NaN     NaN  No tone        -999        person   diningtable   
940         NaN     NaN  No tone        -999          bird          boat   
941         NaN     NaN  No tone        -999        person     aeroplane   
942         NaN     NaN  No tone        -999           car           NaN   
943         NaN     NaN  No tone        -999           car        person   
944         NaN     NaN    tone2         786        person         horse   
945         NaN     NaN  No tone        -999         chair   diningtable   
946         NaN     NaN  No tone        -999        person         horse   
947         NaN     NaN  No tone        -999         chair        bottle   
948         NaN     NaN    tone1         448     tvmonitor   diningtable   
949         NaN     NaN  No tone        -999           dog           NaN   
950         NaN     NaN  No tone        -999           car           cat   
951         NaN     NaN  No tone        -999           cat           NaN   
952         NaN     NaN  No tone        -999          bird

In [2]:
def fix_reaction_times(df):
#     df = pd.DataFrame.from_csv(path, header = None)
#     df.reset_index(inplace = True)
#     df.columns = ['Image_Name','Cat.1','Cat.2','Cat.3','Cat.4','Cat.5','TS','Load','exemplar','question','present_absent','trial_type','tone_Hz','tone_onset','space','RT_TO','keys','RT_VS','useless','Trial_N_Block','Block']

    n = df.shape[0]
    for i in range(n):
        
        trial_type = df['trial_type'][i]
        rt_sound = df['RT_TO'][i]
        if 'Critical' in trial_type and 'No timing' in rt_sound:
            print 'DIRTY!',i
            go = True
            c = i+1
    #         set_trace()
            if c<n and 'Normal' in df['trial_type'][c] and  'No timing' not in df['RT_TO'][c]:

                print 'FOUND RT IN FIRST', c
                df.loc[i,'RT_TO'] = str(float(df.loc[c,'RT_TO']) + 1.3)
                df.loc[i,'space'] = 'space'
                df.loc[c,'RT_TO'] = 'No timing'
                df.loc[c,'space'] = 'No space' 
                go = False
            c = i+2
            if go and c<n and 'Normal' in df['trial_type'][c] and  'No timing' not in df['RT_TO'][c]:
                print 'FOUND RT IN SECOND',c
                df.loc[i,'RT_TO'] = str(float(df.loc[c,'RT_TO']) + 2.6)
                df.loc[i,'space'] = 'space'
                df.loc[c,'RT_TO'] = 'No timing'
                df.loc[c,'space'] = 'No space' 
    return df

        
            
        

In [3]:
def print_full(x):
    pd.set_option('display.max_rows', len(x))
    print(x)
    pd.reset_option('display.max_rows')

In [4]:
df1 = pd.DataFrame.from_csv(mypath+'p1_1.csv', header = None)
df1.reset_index(inplace = True)
df1.columns = ['Image_Name','Cat.1','Cat.2','Cat.3','Cat.4','Cat.5','TS','Load','exemplar','question','present_absent','trial_type','tone_Hz','tone_onset','space','RT_TO','keys','RT_VS','useless','Trial_N_Block','Block']
df1.shape
#df1

(480, 21)

In [5]:
df2 = pd.DataFrame.from_csv(mypath+'p1_2.csv', header = None)
df2.reset_index(inplace = True)
df2.columns = ['Image_Name','Cat.1','Cat.2','Cat.3','Cat.4','Cat.5','TS','Load','exemplar','question','present_absent','trial_type','tone_Hz','tone_onset','space','RT_TO','keys','RT_VS','useless','Trial_N_Block','Block']
df2.shape
#df2

(480, 21)

In [6]:
frames = [df1,df2]
df = pd.concat(frames)
df.reset_index(drop=True, inplace=True)
df.drop(['Image_Name','Cat.1','Cat.2','Cat.3','Cat.4','Cat.5','TS','exemplar','question','space','useless'], axis=1, inplace=True)
fix_reaction_times(df)
df

DIRTY! 2
DIRTY! 22
DIRTY! 24
FOUND RT IN FIRST 25
DIRTY! 91
DIRTY! 93
DIRTY! 107
DIRTY! 160
DIRTY! 172
DIRTY! 207
DIRTY! 209
FOUND RT IN FIRST 210
DIRTY! 242
DIRTY! 245
DIRTY! 253
DIRTY! 258
FOUND RT IN FIRST 259
DIRTY! 308
FOUND RT IN FIRST 309
DIRTY! 319
DIRTY! 322
DIRTY! 336
FOUND RT IN FIRST 337
DIRTY! 338
FOUND RT IN FIRST 339
DIRTY! 379
FOUND RT IN FIRST 380
DIRTY! 417
DIRTY! 440
DIRTY! 443
DIRTY! 451
DIRTY! 493
FOUND RT IN FIRST 494
DIRTY! 526
DIRTY! 532
DIRTY! 541
DIRTY! 548
FOUND RT IN FIRST 549
DIRTY! 637
FOUND RT IN FIRST 638
DIRTY! 646
DIRTY! 710
DIRTY! 761
DIRTY! 794
FOUND RT IN FIRST 795
DIRTY! 810
DIRTY! 828
DIRTY! 837
DIRTY! 841
DIRTY! 869
DIRTY! 901
DIRTY! 907
FOUND RT IN FIRST 908
DIRTY! 911
DIRTY! 929
DIRTY! 934


Load     present_absent   trial_type     tone_Hz  tone_onset  \
0      'low'        'No Target'     'Normal'   'No tone'        -999   
1      'low'    'Target Absent'     'Normal'   'No tone'        -999   
2      'low'        'No Target'   'Critical'     'tone2'         481   
3      'low'        'No Target'     'Normal'   'No tone'        -999   
4      'low'        'No Target'     'Normal'   'No tone'        -999   
5      'low'   'Target Present'     'Normal'   'No tone'        -999   
6      'low'        'No Target'     'Normal'   'No tone'        -999   
7      'low'   'Target Present'     'Normal'   'No tone'        -999   
8      'low'    'Target Absent'     'Normal'   'No tone'        -999   
9      'low'        'No Target'     'Normal'   'No tone'        -999   
10     'low'        'No Target'     'Normal'   'No tone'        -999   
11     'low'        'No Target'     'Normal'   'No tone'        -999   
12     'low'        'No Target'   'Critical'     'tone2'         631   
13     'low'        'No Target'     'Normal'   'No tone'        -999   
14     'low'        'No Target'     'Normal'   'No tone'        -999   
15     'low'        'No Target'   'Critical'     'tone2'         305   
16     'low'        'No Target'     'Normal'   'No tone'        -999   
17     'low'        'No Target'     'Normal'   'No tone'        -999   
18     'low'        'No Target'     'Normal'   'No tone'        -999   
19     'low'        'No Target'     'Normal'   'No tone'        -999   
20     'low'        'No Target'     'Normal'   'No tone'        -999   
21     'low'        'No Target'     'Normal'   'No tone'        -999   
22     'low'        'No Target'   'Critical'     'tone1'          78   
23     'low'        'No Target'     'Normal'   'No tone'        -999   
24     'low'        'No Target'   'Critical'     'tone2'         946   
25     'low'        'No Target'     'Normal'   'No tone'        -999   
26     'low'        'No Target'     'Normal'   'No tone'        -999   
27     'low'        'No Target'     'Normal'   'No tone'        -999   
28     'low'        'No Target'     'Normal'   'No tone'        -999   
29     'low'        'No Target'     'Normal'   'No tone'        -999   
..       ...                ...          ...         ...         ...   
930   'high'        'No Target'     'Normal'   'No tone'        -999   
931   'high'        'No Target'     'Normal'   'No tone'        -999   
932   'high'        'No Target'     'Normal'   'No tone'        -999   
933   'high'        'No Target'     'Normal'   'No tone'        -999   
934   'high'        'No Target'   'Critical'     'tone1'         385   
935   'high'        'No Target'     'Normal'   'No tone'        -999   
936   'high'        'No Target'     'Normal'   'No tone'        -999   
937   'high'   'Target Present'     'Normal'   'No tone'        -999   
938   'high'        'No Target'     'Normal'   'No tone'        -999   
939   'high'        'No Target'     'Normal'   'No tone'        -999   
940   'high'        'No Target'     'Normal'   'No tone'        -999   
941   'high'        'No Target'     'Normal'   'No tone'        -999   
942   'high'        'No Target'     'Normal'   'No tone'        -999   
943   'high'        'No Target'     'Normal'   'No tone'        -999   
944   'high'        'No Target'     'Normal'   'No tone'        -999   
945   'high'        'No Target'     'Normal'   'No tone'        -999   
946   'high'        'No Target'     'Normal'   'No tone'        -999   
947   'high'        'No Target'     'Normal'   'No tone'        -999   
948   'high'        'No Target'     'Normal'   'No tone'        -999   
949   'high'   'Target Present'     'Normal'   'No tone'        -999   
950   'high'        'No Target'     'Normal'   'No tone'        -999   
951   'high'        'No Target'     'Normal'   'No tone'        -999   
952   'high'        'No Target'     'Normal'   'No tone'        -999   
953   'high'        'No Target'     'Normal'   '

In [7]:
RT_TO = df['RT_TO'].tolist()
RT_VS = df['RT_VS'].tolist()
Audio = df['trial_type'].tolist()
Present_absent = df['present_absent'].tolist()
Audio = df['trial_type'].tolist()
Keys = df['keys'].tolist()
Tone_onset = df['tone_onset'].tolist()

In [8]:
RT_TO

[" 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 '1.362520405',
 " 'No timing'",
 " 'No timing'",
 '1.078664931',
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 '1.412410691',
 'No timing',
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 '1.445441479',
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 " 'No timing'",
 '1.

In [9]:
RT_TO = [str('NaN') if 'No timing' in n else float(n[0:5]) for n in RT_TO]

In [10]:
RT_VS = [str('NaN') if 'Na' in n else float(n[0:5])-1.3 for n in RT_VS]

In [11]:
Keys = [str(n[2:-1]) for n in Keys]

In [12]:
RT_TO_floats = [n for n in RT_TO if type(n) == float]
sd_TO = np.std(RT_TO_floats)
mean_TO = np.mean(RT_TO_floats)

In [13]:
#Getting rid of outliers for TO RT (outliers are replaced with mean)
RT_TO_no_outliers = []
counter_TO = 0
RT_TO_outliers = []
for i in RT_TO:
    if type(i) != float:
        RT_TO_no_outliers.append(i)
    elif type(i) == float:
        if (mean_TO - 2.5 * sd_TO) < i < (mean_TO + 2.5 * sd_TO):
            RT_TO_no_outliers.append(i)
        else:
            counter_TO = counter_TO + 1
            #print 'Outlier ' + str(counter_TO) + ': ' + str(i) 
            RT_TO_no_outliers.append(mean_TO)
            RT_TO_outliers.append(i)
RT_TO = RT_TO_no_outliers

In [14]:
Tone_onset = [int(n) for n in Tone_onset]
for i in range(len(Tone_onset)):
    if Tone_onset[i] != -999:
        Tone_onset[i] = float(Tone_onset[i])/1000
        if type(RT_TO[i]) == float:
            #print RT_TO[i], '-', Tone_onset[i] 
            RT_TO[i] = RT_TO[i] - Tone_onset[i]
            #print RT_TO[i]

In [15]:
RT_VS_floats = [n for n in RT_VS if type(n) == float]
sd_VS = np.std(RT_VS_floats)
mean_VS = np.mean(RT_VS_floats)

In [16]:
#Getting rid of outliers for TO RT (outliers are replaced with mean)
RT_VS_no_outliers = []
counter_VS = 0
RT_VS_outliers = []
for i in RT_VS:
    if type(i) != float:
        RT_VS_no_outliers.append(i)
    elif type(i) == float:
        if (mean_VS - 2.5 * sd_VS) < i < (mean_VS + 2.5 * sd_VS):
            RT_VS_no_outliers.append(i)
        else:
            counter_VS = counter_VS + 1
            #print 'Outlier ' + str(counter_TO) + ': ' + str(i) 
            RT_VS_no_outliers.append(mean_VS)
            RT_VS_outliers.append(i)
RT_VS = RT_VS_no_outliers

In [17]:
print 'Take Over:'
print 'mean RT: ', mean_TO
print 'SD: ', sd_TO
print 'Outliers: ', len(RT_TO_outliers)
for i in RT_TO_outliers:
    print i

print 'Visual Search:'
print 'mean RT: ', mean_VS
print 'SD: ', sd_VS
print 'Outliers: ', len(RT_VS_outliers)
for i in RT_VS_outliers:
    print i


Take Over:
mean RT:  1.21444117647
SD:  0.250411800978
Outliers:  0
Visual Search:
mean RT:  0.929076388889
SD:  0.210972848433
Outliers:  4
2.19
1.462
1.478
1.816


In [18]:
for i in RT_TO:
    print i, type(i)

NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.731 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
0.773 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.466 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.895 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'

NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.676 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.636 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
0.687 <type 'float'>
NaN <type 'str'>
1.0 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.74 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
0.632 <type 'float'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 'str'>
NaN <type 

In [19]:
#######
Acc_VS = []
for i in range(960):
    if 'Critical' in Audio[i]:
        #print i
        Acc_VS.append('999')
    elif 'Normal' in Audio[i] and RT_TO[i] != 'NaN':
        Acc_VS.append('666')
    elif 'Target Present' in Present_absent[i] and 'q' in Keys[i]:
        Acc_VS.append(1)
    elif 'Target Present' in Present_absent[i] and 'p' in Keys[i]:
        Acc_VS.append(0)
    elif 'Target Absent' in Present_absent[i] and 'p' in Keys[i]:
        Acc_VS.append(1)   
    elif 'Target Absent' in Present_absent[i] and 'q' in Keys[i]:
        Acc_VS.append(0)
    elif 'No Target' in Present_absent[i]:
        Acc_VS.append('999')

#print len(Acc_VS)
#######

In [20]:
#######
# CREATING Acc_DT (1 = included for analysis; 0 = excluded from analysis)
Acc_DT = []
for i in range(960):
    if 'Critical' in Audio[i] and type(RT_TO[i]) != str:
        if 'Target Present' in Present_absent[i] and 'q' in Keys[i]:
            Acc_DT.append(1)
        elif 'Target Absent' in Present_absent[i] and 'p' in Keys[i]:
            Acc_DT.append(1)
        elif 'Target Present' in Present_absent[i] and 'p' in Keys[i]:
            Acc_DT.append(999)
        elif 'Target Absent' in Present_absent[i] and 'q' in Keys[i]:
            Acc_DT.append(999)
        elif 'No Target' in Present_absent[i]:
            Acc_DT.append(1)
    elif 'Critical' in Audio[i] and type(RT_TO[i]) == str:
        Acc_DT.append(0)
    elif 'Normal' in Audio[i] and type(RT_TO[i]) != str:
        Acc_DT.append(666) # 666 are false alarms
    elif 'Normal' in Audio[i] and type(RT_TO[i]) == str:
        Acc_DT.append(999)
#print len(Acc_DT) 

In [21]:
# Calculating D' :
# to calculate D' prime you need:
#1) hit rate
#2) false alarms rate
# the z-transformed of 1 and 2
# the formula is:....
# 1 and 2 cannot be equal to 1 or 0
correct_response_counter = len([n for n in Acc_DT if n == 1])
incorrect_response_counter = len([n for n in Acc_DT if n == 0])
incorrect_response_counter

32

In [22]:
# Converting lists into pandas.series...
RT_TO = pd.Series(data=RT_TO)
RT_VS = pd.Series(data=RT_VS)
Acc_VS = pd.Series(data=Acc_VS)
Acc_DT = pd.Series(data=Acc_DT)
#False_Alarms = pd.Series(data=False_Alarms)
# ...and combining them into a pandas dataframe

In [23]:
df.drop(['RT_TO','RT_VS'], axis = 1, inplace = True)
df['RT_TO'] = RT_TO.values
df['RT_VS'] = RT_VS.values
df['Acc_VS'] = Acc_VS.values
df['Acc_DT'] = Acc_DT.values

In [24]:
df[['RT_TO','RT_VS']] = df[['RT_TO','RT_VS']].astype('float')
df[['Acc_VS','Acc_DT']] = df[['Acc_VS','Acc_DT']].astype('int')
print df.dtypes

Load               object
present_absent     object
trial_type         object
tone_Hz            object
tone_onset          int64
keys               object
Trial_N_Block       int64
Block               int64
space              object
RT_TO             float64
RT_VS             float64
Acc_VS              int32
Acc_DT              int32
dtype: object


In [25]:
# Calculating D' :
# to calculate D' prime you need:
#1) hit rate
#2) false alarms rate
# the z-transformed of 1 and 2
# the formula is:....
# 1 and 2 cannot be equal to 1 or 0


In [26]:
#TABLE 1
#print df.groupby(['Load','Acc_VS']).RT_VS.mean()
#print df.groupby(['Load','Acc_VS']).RT_VS.count()

# TABLE 2
#print df.groupby(['Load','Acc_VS','present_absent']).RT_VS.mean()
#print df.groupby(['Load','Acc_VS','present_absent']).RT_VS.count()

#TABLE 3
print df.groupby(['Load','trial_type','Acc_DT']).RT_TO.mean()
print df.groupby(['Load','trial_type','Acc_DT']).Acc_DT.count()

#-----------------------------------------------------------------------
#TABLE 4
#print df.groupby(['Load','Audio']).Audio.count()
#print df.groupby(['Load','Audio','Acc_DT']).Acc_DT.count()

Load     trial_type   Acc_DT
 'high'   'Critical'  0              NaN
                      1         0.736793
                      999       0.816000
          'Normal'    666       1.058500
                      999            NaN
 'low'    'Critical'  0              NaN
                      1         0.743588
          'Normal'    666       1.379000
                      999            NaN
Name: RT_TO, dtype: float64
Load     trial_type   Acc_DT
 'high'   'Critical'  0          18
                      1          29
                      999         1
          'Normal'    666         2
                      999       430
 'low'    'Critical'  0          14
                      1          34
          'Normal'    666         2
                      999       430
Name: Acc_DT, dtype: int64


In [34]:
cols = range(5)
rows = range(10)

data = np.zeros((10,5))

In [33]:
print data

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [66]:
def make_table(title, cols, rows, data, f):
    si,sj = data.shape

   
    f.write('<h1>')
    f.write(title)
    f.write('</h1>')
    f.write('<br />')
    f.write('<table border="0">')
    f.write('<tr>')
    f.write('<td></td>')
    for j in range(sj):
        f.write('<td>')
        f.write(str(cols[j]))
        f.write('</td>')
    f.write('</tr>')

    for i in range(si):
        f.write('<tr>')
        f.write('<td>')
        f.write(str(rows[i]))
        f.write('</td>')
        for j in range(sj):
            f.write('<td>')
            f.write(str(data[i,j]))
            f.write('</td>')
        f.write('</tr>')
    f.write('</table>')
    

In [67]:
with open('my_table_2.html','wb') as f:
    f.write('<html><body>')
    make_table('T1',cols,rows,data,f)
    make_table('T1',cols,rows,data,f)
    f.write('</body></html>')

In [35]:
data.shape

(10, 5)

In [69]:
f = open('my_table_3.html','wb')
f.write('<html><body>')
make_table('T1',cols,rows,data,f)
make_table('T1',cols,rows,data,f)
f.write('</body></html>')
f.close()